version: '{build}'

os: Visual Studio 2015

cache:
  - C:\Users\appveyor\.m2 -> .appveyor.yml
  - C:\Downloads -> .appveyor.yml

environment:
  matrix:
    - PROJ: "helloworld"
      OS: windows-x86

    - PROJ: "helloworld"
      OS: windows-x86_64

