.build_template: &build_definition
    script:
        - ./autogen.sh
        - ./configure --prefix=`pwd`/build
        - make distcheck

build:linux:
    image: gcc
    stage: build
    before_script:
        - apt update && apt -y install make autoconf
    <<: *build_definition

build:windows:
    stage: build
    tags:
        - windows
    variables:
        MSYSTEM: "MINGW64"
        CHERE_INVOKING: "yes"
    script:
        - C:\msys64\usr\bin\pacman --noconfirm -Syyuu --ask 20
        - C:\msys64\usr\bin\bash -lc "bash -x ./gitlab.sh"

#build:windows:
#    #image: mback2k/windows-buildbot-msys2
#    image: rwgrim/msys2-cross
#    stage: build
#    before_script:
#        - pacman --noconfirm -Suy
#        - pacman --noconfirm -S --needed base-devel
#    <<: *build_definition
