.build_template: &build_definition
    script:
        - ./autogen.sh
        - ./configure --prefix=`pwd`/build
        - make distcheck

build:linux:
    image: gcc
    stage: build
    before_script:
        - apt update && apt -y install make autoconf
    <<: *build_definition

build:windows:
    #image: mback2k/windows-buildbot-msys2
    #image: rwgrim/msys2-cross
    image: mizarjp/winci-msys2
    stage: build
    before_script:
        - pacman --noconfirm -Suy
        - pacman --noconfirm -S --needed base-devel
    <<: *build_definition
