language: c

matrix:
  include:
  - os: osx
    env: OS_BUILD=osx
  - os: linux
    env: OS_BUILD=linux
  - os: windows
    env: OS_BUILD=windows
    before_install:
    #- choco install -r --no-progress -y msys2
    - export PATH=$PATH:/c/tools/msys64/usr/bin/
    - pacman-key --init
    - pacman-key --populate msys2
    - pacman-key --refresh-keys
    - pacman -Syu --force
    - pacman -S --force --noconfirm --needed base-devel msys2-devel


script:
  - ./autogen.sh && ./configure --prefix=`pwd`/build && make distcheck
